spring:
  # 数据源设置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/chasingthelight?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
  # 邮件配置（以QQ邮箱为例）
  mail:
    host: smtp.qq.com
    port: 587
    username: 2815407040@qq.com  # 替换为你的QQ邮箱
    password: ymjtlacvveylddie  # 替换为邮箱授权码（非登录密码）
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  # Jackson日期格式设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis配置
  data:
    redis:
      host: localhost
      timeout: 3000ms
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 日志设置（显示SQL）
logging:
  level:
    cn.lanqiao.springboot.mapper: debug