spring:
  #数据源设置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/chasingthelight?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver

    #日期格式设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#showSql
logging:
  level:
    cn.lanqiao.springboot.mapper: debug
